---
Name: search_simple_smart
---
Page:
  extensions:
    - Sunnysideup\SearchSimpleSmart\Extensions\SearchEngineMakeSearchable

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\SearchSimpleSmart\Extensions\SearchEngineSiteConfigExtension

SilverStripe\ErrorPage\ErrorPage:
  search_engine_exclude_from_index: true

SilverStripe\CMS\Model\VirtualPage:
  search_engine_exclude_from_index: true

SilverStripe\CMS\Model\RedirectorPage:
  search_engine_exclude_from_index: true
