---
Name: search_simple_smart_routs
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    searchenginerecordclick//$Action/$ID/$Name: Sunnysideup\SearchSimpleSmart\Control\SearchEngineRecordClick
